Find_Resto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import main.urls as main

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(main,namespace='main')),
]

main/urls.py
from django.conf.urls import url
from .views import index, search

#url for app
urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^search/', search, name='search'),
]

main/models.py
from django.db import models

# Create your models here.

class Restaurant(models.Model):
	idResto = models.CharField(max_length=40, default=0)
	name = models.CharField(max_length=1000, default=0)
	city = models.CharField(max_length=100, default=0)
	cuisine = models.CharField(max_length=2000, default=0)
	address = models.CharField(max_length=2000, default=0)
	image = models.CharField(max_length=2000, default=0)

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .zomatopy import *
from .models import Restaurant

config={
  "user_key":"490a023a1e12e898ba70c7bfd3715138"
}

response = {}

# Create your views here.
def index(request):
	html = "landing_page.html"
	return render(request, html, response)

def search(request):
	if request.method == "POST":
		makanan = request.POST.get('food')
		query = makanan.lower().split(" ")

		if Restaurant.objects.all():
			Restaurant.objects.all().delete()
	

		zomato = initialize_app(config)
		cuisine_not_found = False

		list_resto = {}
		ranked = []

		list_resto = zomato.restaurant_search(makanan)

		if list_resto == False or len(list_resto) == 0:
			cuisine_not_found = True
		else:
			ranked = rank_resto(list_resto, query)

		createModel(ranked, list_resto)

		response["cuisine_not_found"] = cuisine_not_found
		response["list_resto"] = Restaurant.objects.all()
				
	return render(request, "result.html", response)


def rank_resto(list_resto, query):
	rank_dict = {}
	rank = []

	for resto_id in list_resto:
		rank_dict[resto_id] = score(list_resto[resto_id], query)

	sort = sorted(rank_dict.items(), key=lambda kv: kv[1])

	for resto in sort:
		rank.append(resto[0])

	return rank

def score(detail_resto, query):
	score = 0
	name = detail_resto["name"].lower().split(" ")
	cuisine = detail_resto["cuisine"].lower().split(", ")

	jmlh_nama_sama = 0
	for kata in name:
		if kata in query:
			# score jika query ada di dalam nama restauran += 0.7
			jmlh_nama_sama += 1

	jmlh_cuisine_sama = 0
	jmlh_cuisine_beda = 0
	for kata in cuisine:
		if kata in query:
			# score jika query ada di dalam cuisine restauran += 0.5
			jmlh_cuisine_sama += 1
		else:
			# score jika cuisine restauran punya hubungan dengan query += 0.1
			jmlh_cuisine_beda += 1

	score += jmlh_nama_sama * 0.7
	score += jmlh_cuisine_sama * 0.5
	score += jmlh_cuisine_beda * 0.1

	return score

def createModel(ranked, list_resto):
	for resto in ranked:
		nama = list_resto[resto]["name"]
		city = list_resto[resto]["city"]
		cuisine = list_resto[resto]["cuisine"]
		address = list_resto[resto]["address"]
		image = list_resto[resto]["image"]

		obj = Restaurant(idResto=resto, name=nama, city=city, cuisine=cuisine, image=image, address=address)
		obj.save()

main/templates/landing_page.html
{% extends "layout/base.html" %}

{% block content %}
<div class="container">
	<div id="group-logo">
		<h1>Find <b class="rectangle-3">Resto</b></h1>
	</div>
	<form action="{% url 'main:search' %}" method="post">
		{% csrf_token %}
		<div class="form-group">
			<input name="food" type="text" class="form-control" id="input" placeholder="Seach Here . . .">
			<button type="submit" class="btn btn-info">Search</button>
		</div>
	</form>
</div>
{% endblock %}

main/templates/layout/base.html
{% load static %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="FindResto">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block css %}<!--add script-->{% endblock %}
    

    <title>
        {% block title %} FindResto {% endblock %}
    </title>
</head>
<body>
    <header>
        {% block header %}
            <!-- {% include "partials/header.html" %} -->
        {% endblock %}
    </header>
    <content>
        {% block content %}
            <!-- content goes here -->
        {% endblock %}
    </content>
    <footer>
        {% block footer %}
            {% include "partials/footer.html" %}
        {% endblock %}
    </footer>
    <!-- Jquery n Bootstrap Script -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block script %}<!--add script-->{% endblock %}
</body>
</html>

main/templates/partials/footer.html
<div class="footer">
</div>
 

main/templates/partials/header.html
<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="{% url 'main:index' %}">FIND <b class="rectangle-3">RESTO</b></a>
</nav>

main/templates/result.html
{% extends "layout/base.html" %}

{% block header %}
	{% include "partials/header.html" %}
{% endblock %}

{% block content %}
<div class="container">
	{% if city_not_found %}
		<div class="jumbotron">
			<div class="alert alert-danger text-center">
				<h2>Maaf Kota Yang Anda Cari</h2>
				<h2>Tidak Ditemukan</h2>
			</div>
		</div>
	{% elif cuisine_not_found %}
		<div class="jumbotron">
			<div class="alert alert-danger text-center">
				<h2>Maaf Makanan Yang Anda Cari</h2>
				<h2>Tidak Ditemukan</h2>
			</div>
		</div>
	{% else %}
		<h2 id="result">RESULT</h2>
		<p>Here’s some restaurant base on your search</p>

		<div class="jumbotron">
			<div class="flex">
				{% for resto in list_resto %}
					<div class="flex-item">
						<div class="to-do-list">
							<div class="to-do-list-title">
								{{ resto.name }}
							</div>
							<div class="to-do-list-description">
								<img id="gambar-resto" src="{{ resto.image }}">
								{{ resto.address }}
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	{% endif %}

</div>
{% endblock %}